
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"rt-MenuItemReview-create-db","number":50,"title":"Add menuItemReview db","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/50"},{"author":{"id":"U_kgDOBXuxxw","is_bot":false,"login":"Cory-Zhao","name":"Cory Zhao"},"headRefName":"CZ-RecommendationRequest-create-controller","number":49,"title":"Create RecommendationRequestController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/49"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-HelpRequestTable-Controller","number":48,"title":"Create HelpRequestController, add GET and POST","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/48"},{"author":{"id":"U_kgDOB7ziew","is_bot":false,"login":"megumi-ondo","name":""},"headRefName":"MO-UCSBOrganization-create-db","number":47,"title":"Create database for UCSBOrganizations","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/47"},{"author":{"id":"U_kgDOB2-3Pg","is_bot":false,"login":"samanthwest","name":""},"headRefName":"Sam-Dining","number":44,"title":"Create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/44"}]
