
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOB2-3Pg","is_bot":false,"login":"samanthwest","name":""},"headRefName":"Sam-Dining-Controller2","number":74,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create), PUT,  and DELETE","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/74"},{"author":{"id":"U_kgDOBdHvhQ","is_bot":false,"login":"anirudhiyer1","name":""},"headRefName":"AnirudhArticlesController","number":73,"title":"Anirudh articles controller- add GET and POST + Added get, put, and delete endpoint and tests for controller #39, #40, #41, #42","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/73"},{"author":{"id":"U_kgDOBdHvhQ","is_bot":false,"login":"anirudhiyer1","name":""},"headRefName":"Anirudh-ArticlesTable","number":68,"title":"Articles table pulled from main. Closes #38","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/68"},{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"rt-MenuItemReview-add-DELETE","number":66,"title":"MenuItemReview add delete","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/66"}]
