
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOB7ziew","is_bot":false,"login":"megumi-ondo","name":""},"headRefName":"MO-UCSBOrganizationController-DELETE","number":72,"title":"Added DELETE for UCSBOrganizations","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/72"},{"author":{"id":"U_kgDOB7ziew","is_bot":false,"login":"megumi-ondo","name":""},"headRefName":"MO-UCSBOrganizationController-PUT","number":71,"title":"Add UCSBOrganization PUT","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/71"},{"author":{"id":"U_kgDOB7ziew","is_bot":false,"login":"megumi-ondo","name":""},"headRefName":"MO-UCSBOrganizationController-GET","number":70,"title":"Add UCSBOrganization GET for single organization","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/70"},{"author":{"id":"U_kgDOB7ziew","is_bot":false,"login":"megumi-ondo","name":""},"headRefName":"MO-UCSBOrganizationController","number":69,"title":"UCSBOrganization add GET and POST","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/69"},{"author":{"id":"U_kgDOBdHvhQ","is_bot":false,"login":"anirudhiyer1","name":""},"headRefName":"Anirudh-ArticlesTable","number":68,"title":"Articles table pulled from main","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/68"},{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"rt-MenuItemReview-add-DELETE","number":66,"title":"MenuItemReview add delete","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/66"},{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"rt-MenuItemReview-add-PUT","number":65,"title":"MenuItemReview Add PUT","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-4/pull/65"}]
